// Generated by CoffeeScript 1.3.3
var ShareJS, ShareJSOpts, connect, port, server;

connect = require('connect');

ShareJS = require('share').server;

ShareJSOpts = require('./options') || {};

server = connect.createServer();

server.use(connect['static'](__dirname + "/static"));

ShareJS.attach(server, ShareJSOpts);

port = 80;

server.listen(port, function() {
  return console.log("Listening on " + port);
});
